apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-github-package-test-backend-deployment
  labels:
    app: k8s-github-package-test-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-github-package-test-backend
  template:
    metadata:
      labels:
        app: k8s-github-package-test-backend
    spec:
      containers:
        - name: k8s-github-package-test-backend
          image: ghcr.io/tuvsheezz/k8s-github-package-test-backend:main
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: dockerconfigjson-secret
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-github-package-test-backend-service
spec:
  selector:
    app: k8s-github-package-test-backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
