apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-github-package-test-frontend-deployment
  labels:
    app: k8s-github-package-test-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-github-package-test-frontend
  template:
    metadata:
      labels:
        app: k8s-github-package-test-frontend
    spec:
      containers:
        - name: k8s-github-package-test-frontend
          image: ghcr.io/tuvsheezz/k8s-github-package-test-frontend:main
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: dockerconfigjson-secret
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-github-package-test-frontend-service
spec:
  selector:
    app: k8s-github-package-test-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
